# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_multinode.ui'
#
# Created: Thu Apr 09 10:12:41 2015
#      by: PyQt4 UI code generator 4.10
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MultiNode(object):
    def setupUi(self, MultiNode):
        MultiNode.setObjectName(_fromUtf8("MultiNode"))
        MultiNode.setEnabled(True)
        MultiNode.resize(489, 505)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Tahoma"))
        font.setPointSize(13)
        MultiNode.setFont(font)
        MultiNode.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        MultiNode.setWindowTitle(_fromUtf8("iSimGis Converter"))
        MultiNode.setWindowOpacity(4.0)
        MultiNode.setToolTip(_fromUtf8(""))
        MultiNode.setStatusTip(_fromUtf8(""))
        MultiNode.setSizeGripEnabled(False)
        self.gridLayout_4 = QtGui.QGridLayout(MultiNode)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.tabWidget = QtGui.QTabWidget(MultiNode)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMaximumSize(QtCore.QSize(471, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(12)
        self.tabWidget.setFont(font)
        self.tabWidget.setIconSize(QtCore.QSize(16, 16))
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.TrafficLightIDlabel = QtGui.QLabel(self.tab)
        self.TrafficLightIDlabel.setGeometry(QtCore.QRect(10, 140, 111, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(12)
        self.TrafficLightIDlabel.setFont(font)
        self.TrafficLightIDlabel.setObjectName(_fromUtf8("TrafficLightIDlabel"))
        self.NodeTypelabel = QtGui.QLabel(self.tab)
        self.NodeTypelabel.setGeometry(QtCore.QRect(10, 90, 81, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(12)
        self.NodeTypelabel.setFont(font)
        self.NodeTypelabel.setObjectName(_fromUtf8("NodeTypelabel"))
        self.nodeType = QtGui.QComboBox(self.tab)
        self.nodeType.setGeometry(QtCore.QRect(90, 90, 361, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(12)
        self.nodeType.setFont(font)
        self.nodeType.setObjectName(_fromUtf8("nodeType"))
        self.nodeType.addItem(_fromUtf8(""))
        self.nodeType.addItem(_fromUtf8(""))
        self.nodeType.addItem(_fromUtf8(""))
        self.nodeType.addItem(_fromUtf8(""))
        self.nodeType.addItem(_fromUtf8(""))
        self.trafficLightID = QtGui.QLineEdit(self.tab)
        self.trafficLightID.setGeometry(QtCore.QRect(130, 140, 101, 21))
        self.trafficLightID.setObjectName(_fromUtf8("trafficLightID"))
        self.attributeGroup = QtGui.QGroupBox(self.tab)
        self.attributeGroup.setGeometry(QtCore.QRect(1, 28, 463, 45))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(12)
        self.attributeGroup.setFont(font)
        self.attributeGroup.setTitle(_fromUtf8(""))
        self.attributeGroup.setObjectName(_fromUtf8("attributeGroup"))
        self.gridLayout = QtGui.QGridLayout(self.attributeGroup)
        self.gridLayout.setMargin(5)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.nodeIdLabel = QtGui.QLabel(self.attributeGroup)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(12)
        self.nodeIdLabel.setFont(font)
        self.nodeIdLabel.setObjectName(_fromUtf8("nodeIdLabel"))
        self.horizontalLayout.addWidget(self.nodeIdLabel)
        self.nodeId = QtGui.QLineEdit(self.attributeGroup)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(11)
        self.nodeId.setFont(font)
        self.nodeId.setObjectName(_fromUtf8("nodeId"))
        self.horizontalLayout.addWidget(self.nodeId)
        self.aimsunIdLabel = QtGui.QLabel(self.attributeGroup)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(12)
        self.aimsunIdLabel.setFont(font)
        self.aimsunIdLabel.setObjectName(_fromUtf8("aimsunIdLabel"))
        self.horizontalLayout.addWidget(self.aimsunIdLabel)
        self.aimsunId = QtGui.QLineEdit(self.attributeGroup)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(11)
        self.aimsunId.setFont(font)
        self.aimsunId.setObjectName(_fromUtf8("aimsunId"))
        self.horizontalLayout.addWidget(self.aimsunId)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.splitter = QtGui.QSplitter(self.tab)
        self.splitter.setGeometry(QtCore.QRect(290, 390, 121, 29))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(11)
        self.splitter.setFont(font)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.errorMessage = QtGui.QLabel(self.splitter)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(11)
        font.setItalic(True)
        self.errorMessage.setFont(font)
        self.errorMessage.setStyleSheet(_fromUtf8("color: rgb(255, 20, 27)"))
        self.errorMessage.setText(_fromUtf8(""))
        self.errorMessage.setObjectName(_fromUtf8("errorMessage"))
        self.actionButton = QtGui.QPushButton(self.splitter)
        self.actionButton.setMaximumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(11)
        self.actionButton.setFont(font)
        self.actionButton.setObjectName(_fromUtf8("actionButton"))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.turningGroup = QtGui.QGroupBox(self.tab_3)
        self.turningGroup.setGeometry(QtCore.QRect(0, 10, 451, 121))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(11)
        self.turningGroup.setFont(font)
        self.turningGroup.setObjectName(_fromUtf8("turningGroup"))
        self.turningGroupIDlabel = QtGui.QLabel(self.turningGroup)
        self.turningGroupIDlabel.setGeometry(QtCore.QRect(10, 30, 111, 17))
        self.turningGroupIDlabel.setObjectName(_fromUtf8("turningGroupIDlabel"))
        self.turningGroupID = QtGui.QLineEdit(self.turningGroup)
        self.turningGroupID.setGeometry(QtCore.QRect(130, 29, 101, 21))
        self.turningGroupID.setObjectName(_fromUtf8("turningGroupID"))
        self.fromLinklabel = QtGui.QLabel(self.turningGroup)
        self.fromLinklabel.setGeometry(QtCore.QRect(10, 60, 61, 20))
        self.fromLinklabel.setObjectName(_fromUtf8("fromLinklabel"))
        self.fromLink = QtGui.QComboBox(self.turningGroup)
        self.fromLink.setGeometry(QtCore.QRect(80, 60, 151, 22))
        self.fromLink.setObjectName(_fromUtf8("fromLink"))
        self.toLinklabel = QtGui.QLabel(self.turningGroup)
        self.toLinklabel.setGeometry(QtCore.QRect(240, 60, 51, 20))
        self.toLinklabel.setObjectName(_fromUtf8("toLinklabel"))
        self.toLink = QtGui.QComboBox(self.turningGroup)
        self.toLink.setGeometry(QtCore.QRect(290, 60, 151, 22))
        self.toLink.setObjectName(_fromUtf8("toLink"))
        self.Phaseslabel = QtGui.QLabel(self.turningGroup)
        self.Phaseslabel.setGeometry(QtCore.QRect(10, 90, 47, 21))
        self.Phaseslabel.setObjectName(_fromUtf8("Phaseslabel"))
        self.Rules = QtGui.QComboBox(self.turningGroup)
        self.Rules.setGeometry(QtCore.QRect(290, 90, 151, 22))
        self.Rules.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToContentsOnFirstShow)
        self.Rules.setObjectName(_fromUtf8("Rules"))
        self.Rules.addItem(_fromUtf8(""))
        self.Rules.addItem(_fromUtf8(""))
        self.Rules.addItem(_fromUtf8(""))
        self.Rules.addItem(_fromUtf8(""))
        self.Ruleslabel = QtGui.QLabel(self.turningGroup)
        self.Ruleslabel.setGeometry(QtCore.QRect(240, 90, 47, 21))
        self.Ruleslabel.setObjectName(_fromUtf8("Ruleslabel"))
        self.newturningGroup = QtGui.QPushButton(self.turningGroup)
        self.newturningGroup.setGeometry(QtCore.QRect(240, 30, 75, 23))
        self.newturningGroup.setObjectName(_fromUtf8("newturningGroup"))
        self.Phases = QtGui.QLineEdit(self.turningGroup)
        self.Phases.setGeometry(QtCore.QRect(80, 90, 151, 20))
        self.Phases.setObjectName(_fromUtf8("Phases"))
        self.TurningGroupTable = QtGui.QTableWidget(self.tab_3)
        self.TurningGroupTable.setGeometry(QtCore.QRect(10, 140, 431, 91))
        self.TurningGroupTable.setObjectName(_fromUtf8("TurningGroupTable"))
        self.TurningGroupTable.setColumnCount(0)
        self.TurningGroupTable.setRowCount(0)
        self.turningPath = QtGui.QGroupBox(self.tab_3)
        self.turningPath.setGeometry(QtCore.QRect(0, 250, 451, 101))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(11)
        self.turningPath.setFont(font)
        self.turningPath.setFlat(False)
        self.turningPath.setCheckable(False)
        self.turningPath.setObjectName(_fromUtf8("turningPath"))
        self.TurningPathIDlabel = QtGui.QLabel(self.turningPath)
        self.TurningPathIDlabel.setGeometry(QtCore.QRect(10, 30, 111, 17))
        self.TurningPathIDlabel.setObjectName(_fromUtf8("TurningPathIDlabel"))
        self.TurningPath = QtGui.QLineEdit(self.turningPath)
        self.TurningPath.setGeometry(QtCore.QRect(130, 30, 101, 20))
        self.TurningPath.setObjectName(_fromUtf8("TurningPath"))
        self.fromLanelabel = QtGui.QLabel(self.turningPath)
        self.fromLanelabel.setGeometry(QtCore.QRect(10, 60, 61, 20))
        self.fromLanelabel.setObjectName(_fromUtf8("fromLanelabel"))
        self.fromLane = QtGui.QComboBox(self.turningPath)
        self.fromLane.setGeometry(QtCore.QRect(80, 60, 151, 22))
        self.fromLane.setObjectName(_fromUtf8("fromLane"))
        self.toLanelabel = QtGui.QLabel(self.turningPath)
        self.toLanelabel.setGeometry(QtCore.QRect(240, 60, 51, 20))
        self.toLanelabel.setObjectName(_fromUtf8("toLanelabel"))
        self.toLane = QtGui.QComboBox(self.turningPath)
        self.toLane.setGeometry(QtCore.QRect(290, 60, 151, 22))
        self.toLane.setObjectName(_fromUtf8("toLane"))
        self.newTurningPath = QtGui.QPushButton(self.turningPath)
        self.newTurningPath.setGeometry(QtCore.QRect(240, 30, 75, 23))
        self.newTurningPath.setObjectName(_fromUtf8("newTurningPath"))
        self.TurningPathTable = QtGui.QTableWidget(self.tab_3)
        self.TurningPathTable.setGeometry(QtCore.QRect(10, 350, 431, 91))
        self.TurningPathTable.setObjectName(_fromUtf8("TurningPathTable"))
        self.TurningPathTable.setColumnCount(0)
        self.TurningPathTable.setRowCount(0)
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.gridLayout_4.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.TrafficLightIDlabel.setBuddy(self.trafficLightID)
        self.NodeTypelabel.setBuddy(self.nodeType)
        self.nodeIdLabel.setBuddy(self.nodeId)
        self.aimsunIdLabel.setBuddy(self.aimsunId)
        self.turningGroupIDlabel.setBuddy(self.turningGroupID)
        self.fromLinklabel.setBuddy(self.fromLink)
        self.toLinklabel.setBuddy(self.toLink)
        self.Phaseslabel.setBuddy(self.Phases)
        self.Ruleslabel.setBuddy(self.Rules)
        self.TurningPathIDlabel.setBuddy(self.TurningPath)
        self.fromLanelabel.setBuddy(self.fromLane)
        self.toLanelabel.setBuddy(self.toLane)

        self.retranslateUi(MultiNode)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MultiNode)

    def retranslateUi(self, MultiNode):
        self.TrafficLightIDlabel.setText(_translate("MultiNode", "Traffic Light ID", None))
        self.NodeTypelabel.setText(_translate("MultiNode", "Node Type", None))
        self.nodeType.setItemText(0, _translate("MultiNode", "Default Node", None))
        self.nodeType.setItemText(1, _translate("MultiNode", "Urban Intersection with Signal", None))
        self.nodeType.setItemText(2, _translate("MultiNode", "Urban Intersection without signal", None))
        self.nodeType.setItemText(3, _translate("MultiNode", "Priority Merge Node", None))
        self.nodeType.setItemText(4, _translate("MultiNode", "Non-Priority Merge Node", None))
        self.nodeIdLabel.setText(_translate("MultiNode", "Node Id*", None))
        self.aimsunIdLabel.setText(_translate("MultiNode", "Aimsun Id*", None))
        self.actionButton.setText(_translate("MultiNode", "ADD", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MultiNode", "Node", None))
        self.turningGroup.setTitle(_translate("MultiNode", "Turning Group", None))
        self.turningGroupIDlabel.setText(_translate("MultiNode", "Turning Group ID", None))
        self.fromLinklabel.setText(_translate("MultiNode", "fromLink", None))
        self.toLinklabel.setText(_translate("MultiNode", "toLink", None))
        self.Phaseslabel.setText(_translate("MultiNode", "Phases", None))
        self.Rules.setItemText(0, _translate("MultiNode", "1", None))
        self.Rules.setItemText(1, _translate("MultiNode", "2", None))
        self.Rules.setItemText(2, _translate("MultiNode", "3", None))
        self.Rules.setItemText(3, _translate("MultiNode", "4", None))
        self.Ruleslabel.setText(_translate("MultiNode", "Rules", None))
        self.newturningGroup.setText(_translate("MultiNode", "Add new", None))
        self.turningPath.setTitle(_translate("MultiNode", "Turning Path", None))
        self.TurningPathIDlabel.setText(_translate("MultiNode", "Turning Path ID", None))
        self.fromLanelabel.setText(_translate("MultiNode", "fromLane", None))
        self.toLanelabel.setText(_translate("MultiNode", "toLane", None))
        self.newTurningPath.setText(_translate("MultiNode", "Add new", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MultiNode", "Turnings", None))

