# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_segment.ui'
#
# Created: Tue Mar 24 16:18:33 2015
#      by: PyQt4 UI code generator 4.10
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Segment(object):
    def setupUi(self, Segment):
        Segment.setObjectName(_fromUtf8("Segment"))
        Segment.setEnabled(True)
        Segment.resize(484, 340)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Tahoma"))
        font.setPointSize(13)
        Segment.setFont(font)
        Segment.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        Segment.setWindowTitle(_fromUtf8("iSimGis Converter"))
        Segment.setWindowOpacity(4.0)
        Segment.setToolTip(_fromUtf8(""))
        Segment.setStatusTip(_fromUtf8(""))
        Segment.setSizeGripEnabled(False)
        self.tabWidget_2 = QtGui.QTabWidget(Segment)
        self.tabWidget_2.setGeometry(QtCore.QRect(0, 0, 491, 341))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(12)
        self.tabWidget_2.setFont(font)
        self.tabWidget_2.setObjectName(_fromUtf8("tabWidget_2"))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.titleLabel = QtGui.QLabel(self.tab_2)
        self.titleLabel.setGeometry(QtCore.QRect(130, -40, 91, 17))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.titleLabel.setFont(font)
        self.titleLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.titleLabel.setObjectName(_fromUtf8("titleLabel"))
        self.errorMessage_2 = QtGui.QLabel(self.tab_2)
        self.errorMessage_2.setGeometry(QtCore.QRect(-50, 230, 6, 18))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(12)
        font.setItalic(True)
        self.errorMessage_2.setFont(font)
        self.errorMessage_2.setStyleSheet(_fromUtf8("color: rgb(255, 20, 27)"))
        self.errorMessage_2.setText(_fromUtf8(""))
        self.errorMessage_2.setObjectName(_fromUtf8("errorMessage_2"))
        self.linkGroupBox = QtGui.QGroupBox(self.tab_2)
        self.linkGroupBox.setGeometry(QtCore.QRect(20, 10, 461, 39))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(12)
        self.linkGroupBox.setFont(font)
        self.linkGroupBox.setTitle(_fromUtf8(""))
        self.linkGroupBox.setObjectName(_fromUtf8("linkGroupBox"))
        self.linkIdLabel = QtGui.QLabel(self.linkGroupBox)
        self.linkIdLabel.setGeometry(QtCore.QRect(6, 6, 53, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(12)
        self.linkIdLabel.setFont(font)
        self.linkIdLabel.setObjectName(_fromUtf8("linkIdLabel"))
        self.linkIdComboBox = QtGui.QComboBox(self.linkGroupBox)
        self.linkIdComboBox.setGeometry(QtCore.QRect(64, 6, 381, 27))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(12)
        self.linkIdComboBox.setFont(font)
        self.linkIdComboBox.setObjectName(_fromUtf8("linkIdComboBox"))
        self.actionButton_2 = QtGui.QPushButton(self.tab_2)
        self.actionButton_2.setGeometry(QtCore.QRect(30, 250, 91, 25))
        self.actionButton_2.setMaximumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(12)
        self.actionButton_2.setFont(font)
        self.actionButton_2.setObjectName(_fromUtf8("actionButton_2"))
        self.attributeGroup_2 = QtGui.QGroupBox(self.tab_2)
        self.attributeGroup_2.setGeometry(QtCore.QRect(20, 70, 461, 145))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(12)
        self.attributeGroup_2.setFont(font)
        self.attributeGroup_2.setTitle(_fromUtf8(""))
        self.attributeGroup_2.setObjectName(_fromUtf8("attributeGroup_2"))
        self.label_11 = QtGui.QLabel(self.attributeGroup_2)
        self.label_11.setGeometry(QtCore.QRect(250, 110, 75, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.comboBox_5 = QtGui.QComboBox(self.attributeGroup_2)
        self.comboBox_5.setGeometry(QtCore.QRect(320, 110, 131, 27))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(12)
        self.comboBox_5.setFont(font)
        self.comboBox_5.setObjectName(_fromUtf8("comboBox_5"))
        self.maxSpeed_2 = QtGui.QLineEdit(self.attributeGroup_2)
        self.maxSpeed_2.setGeometry(QtCore.QRect(120, 40, 111, 27))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(12)
        self.maxSpeed_2.setFont(font)
        self.maxSpeed_2.setObjectName(_fromUtf8("maxSpeed_2"))
        self.length = QtGui.QLineEdit(self.attributeGroup_2)
        self.length.setGeometry(QtCore.QRect(320, 80, 131, 27))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(12)
        self.length.setFont(font)
        self.length.setObjectName(_fromUtf8("length"))
        self.maxSpeed = QtGui.QLineEdit(self.attributeGroup_2)
        self.maxSpeed.setGeometry(QtCore.QRect(117, 77, 111, 27))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(12)
        self.maxSpeed.setFont(font)
        self.maxSpeed.setObjectName(_fromUtf8("maxSpeed"))
        self.comboBox_8 = QtGui.QComboBox(self.attributeGroup_2)
        self.comboBox_8.setGeometry(QtCore.QRect(118, 112, 111, 27))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(12)
        self.comboBox_8.setFont(font)
        self.comboBox_8.setObjectName(_fromUtf8("comboBox_8"))
        self.comboBox_8.addItem(_fromUtf8(""))
        self.comboBox_8.addItem(_fromUtf8(""))
        self.comboBox_8.addItem(_fromUtf8(""))
        self.comboBox_8.addItem(_fromUtf8(""))
        self.maxSpeedLabel = QtGui.QLabel(self.attributeGroup_2)
        self.maxSpeedLabel.setGeometry(QtCore.QRect(7, 77, 84, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(12)
        self.maxSpeedLabel.setFont(font)
        self.maxSpeedLabel.setObjectName(_fromUtf8("maxSpeedLabel"))
        self.startNodeLabel = QtGui.QLabel(self.attributeGroup_2)
        self.startNodeLabel.setGeometry(QtCore.QRect(7, 42, 91, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(12)
        self.startNodeLabel.setFont(font)
        self.startNodeLabel.setObjectName(_fromUtf8("startNodeLabel"))
        self.lengthLabel = QtGui.QLabel(self.attributeGroup_2)
        self.lengthLabel.setGeometry(QtCore.QRect(250, 80, 63, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(12)
        self.lengthLabel.setFont(font)
        self.lengthLabel.setObjectName(_fromUtf8("lengthLabel"))
        self.widthLabel = QtGui.QLabel(self.attributeGroup_2)
        self.widthLabel.setGeometry(QtCore.QRect(7, 112, 91, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(12)
        self.widthLabel.setFont(font)
        self.widthLabel.setObjectName(_fromUtf8("widthLabel"))
        self.idLabel = QtGui.QLabel(self.attributeGroup_2)
        self.idLabel.setGeometry(QtCore.QRect(7, 3, 20, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(12)
        self.idLabel.setFont(font)
        self.idLabel.setObjectName(_fromUtf8("idLabel"))
        self.id = QtGui.QLineEdit(self.attributeGroup_2)
        self.id.setGeometry(QtCore.QRect(40, 0, 150, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(12)
        self.id.setFont(font)
        self.id.setObjectName(_fromUtf8("id"))
        self.aimsunIdLabel_2 = QtGui.QLabel(self.attributeGroup_2)
        self.aimsunIdLabel_2.setGeometry(QtCore.QRect(209, 4, 68, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(12)
        self.aimsunIdLabel_2.setFont(font)
        self.aimsunIdLabel_2.setObjectName(_fromUtf8("aimsunIdLabel_2"))
        self.aimsunId_2 = QtGui.QLineEdit(self.attributeGroup_2)
        self.aimsunId_2.setGeometry(QtCore.QRect(290, 0, 161, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(12)
        self.aimsunId_2.setFont(font)
        self.aimsunId_2.setObjectName(_fromUtf8("aimsunId_2"))
        self.tabWidget_2.addTab(self.tab_2, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.label = QtGui.QLabel(self.tab_4)
        self.label.setGeometry(QtCore.QRect(20, 20, 111, 16))
        self.label.setObjectName(_fromUtf8("label"))
        self.lineEdit = QtGui.QLineEdit(self.tab_4)
        self.lineEdit.setGeometry(QtCore.QRect(130, 49, 201, 21))
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.label_2 = QtGui.QLabel(self.tab_4)
        self.label_2.setGeometry(QtCore.QRect(50, 50, 61, 20))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(self.tab_4)
        self.label_3.setGeometry(QtCore.QRect(50, 90, 81, 20))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.comboBox = QtGui.QComboBox(self.tab_4)
        self.comboBox.setGeometry(QtCore.QRect(130, 90, 121, 22))
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.label_4 = QtGui.QLabel(self.tab_4)
        self.label_4.setGeometry(QtCore.QRect(270, 90, 61, 20))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.comboBox_2 = QtGui.QComboBox(self.tab_4)
        self.comboBox_2.setGeometry(QtCore.QRect(340, 90, 121, 22))
        self.comboBox_2.setObjectName(_fromUtf8("comboBox_2"))
        self.label_5 = QtGui.QLabel(self.tab_4)
        self.label_5.setGeometry(QtCore.QRect(50, 120, 81, 20))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_6 = QtGui.QLabel(self.tab_4)
        self.label_6.setGeometry(QtCore.QRect(270, 120, 61, 20))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.comboBox_3 = QtGui.QComboBox(self.tab_4)
        self.comboBox_3.setGeometry(QtCore.QRect(340, 120, 121, 22))
        self.comboBox_3.setObjectName(_fromUtf8("comboBox_3"))
        self.comboBox_4 = QtGui.QComboBox(self.tab_4)
        self.comboBox_4.setGeometry(QtCore.QRect(130, 120, 121, 22))
        self.comboBox_4.setObjectName(_fromUtf8("comboBox_4"))
        self.tableView = QtGui.QTableView(self.tab_4)
        self.tableView.setGeometry(QtCore.QRect(30, 170, 431, 111))
        self.tableView.setObjectName(_fromUtf8("tableView"))
        self.pushButton = QtGui.QPushButton(self.tab_4)
        self.pushButton.setGeometry(QtCore.QRect(364, 50, 91, 23))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.tabWidget_2.addTab(self.tab_4, _fromUtf8(""))

        self.retranslateUi(Segment)
        self.tabWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Segment)

    def retranslateUi(self, Segment):
        self.titleLabel.setText(_translate("Segment", "SEGMENT", None))
        self.linkIdLabel.setText(_translate("Segment", "LinkId*", None))
        self.actionButton_2.setText(_translate("Segment", "ADD", None))
        self.label_11.setText(_translate("Segment", "Category*", None))
        self.comboBox_8.setItemText(0, _translate("Segment", "Default", None))
        self.comboBox_8.setItemText(1, _translate("Segment", "Freeway", None))
        self.comboBox_8.setItemText(2, _translate("Segment", "Ramp", None))
        self.comboBox_8.setItemText(3, _translate("Segment", "Urban Road", None))
        self.maxSpeedLabel.setText(_translate("Segment", "MaxSpeed*", None))
        self.startNodeLabel.setText(_translate("Segment", "SequenceNo*", None))
        self.lengthLabel.setText(_translate("Segment", "Capacity*", None))
        self.widthLabel.setText(_translate("Segment", "Road Type*", None))
        self.idLabel.setText(_translate("Segment", "Id*", None))
        self.aimsunIdLabel_2.setText(_translate("Segment", "Aimsun Id*", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_2), _translate("Segment", "Section", None))
        self.label.setText(_translate("Segment", "Lane Connectors", None))
        self.label_2.setText(_translate("Segment", "Lane ID", None))
        self.label_3.setText(_translate("Segment", "fromSection", None))
        self.label_4.setText(_translate("Segment", "toSection", None))
        self.label_5.setText(_translate("Segment", "fromLane", None))
        self.label_6.setText(_translate("Segment", "toLane", None))
        self.pushButton.setText(_translate("Segment", "ADD NEW", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_4), _translate("Segment", "Connectors", None))

